import { cardLabel, type Subscription } from "./types";

function iso(now: Date, offset: number): string {
  const utc = Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate() + offset,
  );
  return new Date(utc).toISOString().slice(0, 10);
}

export function createSample(now = new Date()): Subscription[] {
  return [
    {
      id: "seed-netflix",
      name: "Netflix",
      amount: 98,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "entertainment",
      nextBillingDate: iso(now, 7),
      startedAt: iso(now, -420),
      url: "https://www.netflix.com",
      paymentVia: {
        kind: "card",
        network: "visa",
        last4: "4242",
        label: cardLabel("visa", "4242"),
      },
    },
    {
      id: "seed-spotify",
      name: "Spotify",
      amount: 58,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "entertainment",
      nextBillingDate: iso(now, 2),
      startedAt: iso(now, -610),
      url: "https://www.spotify.com",
      paymentVia: {
        kind: "card",
        network: "mastercard",
        last4: "5555",
        label: cardLabel("mastercard", "5555"),
      },
    },
    {
      id: "seed-youtube",
      name: "YouTube Premium",
      amount: 88,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "entertainment",
      nextBillingDate: iso(now, 14),
      startedAt: iso(now, -280),
      url: "https://www.youtube.com/premium",
    },
    {
      id: "seed-nowe",
      name: "Now E",
      amount: 88,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "entertainment",
      nextBillingDate: iso(now, 19),
      startedAt: iso(now, -200),
      url: "https://www.nowe.com",
    },
    {
      id: "seed-icloud",
      name: "iCloud+",
      amount: 23,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "cloud",
      nextBillingDate: iso(now, 4),
      startedAt: iso(now, -800),
    },
    {
      id: "seed-google-one",
      name: "Google One",
      amount: 78,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "cloud",
      nextBillingDate: iso(now, 11),
      startedAt: iso(now, -365),
    },
    {
      id: "seed-chatgpt",
      name: "ChatGPT Plus",
      amount: 20,
      currency: "USD",
      cycle: "monthly",
      status: "active",
      category: "software",
      nextBillingDate: iso(now, 9),
      startedAt: iso(now, -180),
      url: "https://chatgpt.com",
      paymentVia: {
        kind: "card",
        network: "amex",
        last4: "1003",
        label: cardLabel("amex", "1003"),
      },
    },
    {
      id: "seed-copilot",
      name: "GitHub Copilot",
      amount: 10,
      currency: "USD",
      cycle: "monthly",
      status: "active",
      category: "software",
      nextBillingDate: iso(now, 5),
      startedAt: iso(now, -240),
      url: "https://github.com/features/copilot",
    },
    {
      id: "seed-adobe",
      name: "Adobe Creative Cloud",
      amount: 54.99,
      currency: "USD",
      cycle: "monthly",
      status: "active",
      category: "software",
      nextBillingDate: iso(now, 8),
      startedAt: iso(now, -500),
      url: "https://www.adobe.com",
      paymentVia: {
        kind: "card",
        network: "unionpay",
        last4: "8888",
        label: cardLabel("unionpay", "8888"),
      },
    },
    {
      id: "seed-1password",
      name: "1Password",
      amount: 36,
      currency: "USD",
      cycle: "yearly",
      status: "active",
      category: "software",
      nextBillingDate: iso(now, 48),
      startedAt: iso(now, -700),
      url: "https://1password.com",
    },
    {
      id: "seed-csl",
      name: "CSL 5G",
      amount: 198,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "utilities",
      nextBillingDate: iso(now, 21),
      startedAt: iso(now, -900),
      notes: "Family SIM",
      paymentVia: {
        kind: "card",
        network: "visa",
        last4: "4242",
        issuer: "HSBC",
        label: cardLabel("visa", "4242", "HSBC"),
      },
    },
    {
      id: "seed-pure",
      name: "Pure Fitness",
      amount: 880,
      currency: "HKD",
      cycle: "monthly",
      status: "active",
      category: "health",
      nextBillingDate: iso(now, 3),
      startedAt: iso(now, -150),
    },
    {
      id: "seed-notion",
      name: "Notion AI",
      amount: 10,
      currency: "USD",
      cycle: "monthly",
      status: "trial",
      category: "software",
      nextBillingDate: iso(now, 4),
      startedAt: iso(now, -10),
      trialEndsAt: iso(now, 4),
      notes: "Converts unless cancelled",
    },
    {
      id: "seed-disney",
      name: "Disney+",
      amount: 78,
      currency: "HKD",
      cycle: "monthly",
      status: "paused",
      category: "entertainment",
      nextBillingDate: iso(now, 12),
      startedAt: iso(now, -320),
    },
    {
      id: "seed-linkedin",
      name: "LinkedIn Premium",
      amount: 29.99,
      currency: "USD",
      cycle: "monthly",
      status: "cancelled",
      category: "software",
      nextBillingDate: iso(now, -18),
      startedAt: iso(now, -400),
    },
  ];
}

export type Suggestion = Pick<
  Subscription,
  "name" | "amount" | "currency" | "cycle" | "category" | "url"
>;

export const CATALOG_SUGGESTIONS: Suggestion[] = [
  {
    name: "Apple One",
    amount: 95,
    currency: "HKD",
    cycle: "monthly",
    category: "entertainment",
    url: "https://www.apple.com/apple-one",
  },
  {
    name: "Microsoft 365",
    amount: 69,
    currency: "HKD",
    cycle: "monthly",
    category: "software",
  },
  {
    name: "SCMP",
    amount: 45,
    currency: "HKD",
    cycle: "monthly",
    category: "news",
    url: "https://www.scmp.com",
  },
  {
    name: "Dropbox",
    amount: 12,
    currency: "USD",
    cycle: "monthly",
    category: "cloud",
  },
  {
    name: "The Athletic",
    amount: 8,
    currency: "USD",
    cycle: "monthly",
    category: "news",
  },
  {
    name: "iCloud+",
    amount: 23,
    currency: "HKD",
    cycle: "monthly",
    category: "cloud",
  },
];
